apiVersion: modules.krateo.io/v1alpha1
kind: Core
metadata:
  name: krateo-module-core
spec:
  compositionSelector:
    matchLabels:
      provider: openshift
  organization: Krateo PlatformOps Company
  frontendUrl: https://krateo-dashboard.krateo.io
  frontend:
    service:
      type: ClusterIP
  backendUrl: https://krateo-dashboard.krateo.io
  backend:
    service:
      type: ClusterIP
  ingress:
    enabled: false
  lighthouse:
    enabled: false
  providers:
    github:
      clientId: xx
      clientSecret: xx
      token: xx
  argo-cd:
    version: 3.33.1
  krateo-dashboard:
    postgresql:
      volumePermissions:
        enabled: false
        securityContext:
          runAsUser: "auto"
      securityContext:
        enabled: false
      shmVolume:
        chmod:
          enabled: false
      containerSecurityContext:
        enabled: false
    version: 0.3.132
  #   keptn:
  #     bridge: http://keptn.krateoplatformops.io/bridge/api/
  #     api: http://keptn.krateoplatformops.io/api/v1/
  #     bridgeToken: Basic <token>
  #     apiToken: dr7cIOBrXMHcs5Axhl4pjD1tIFSK5pfuOPstIMy0HaxbR
