apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: krateo-module-core
spec:
  package: registry.hub.docker.com/ettorefoti/krateo-test:latest
  packagePullPolicy: Always
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
