apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
#  name: demostacks.gcp-stack-template-plus.projectkerberus.io
  name: core.modules.krateoplatformops.io
spec:
  connectionSecretKeys:
    - kubeconfig
#  group: gcp-stack-template-plus.projectkerberus.io
  group: modules.krateoplatformops.io
  names:
#    kind: DemoStack
#    listKind: DemoStackList
#    plural: demostacks
#    singular: demostack
    kind: Core
    listKind: CoreList
    plural: core
    singular: core
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: Core module of Krateo PlatformOps
          type: object
          properties:
            spec:
              type: object
              # properties:
              #   organization:
              #     description: Organization
              #     type: string
                # frontendUrl:
                #   description: Kerberus Dashboard frontend url
                #   type: string
                # backendUrl:
                #   description: Kerberus Dashboard backend url
                #   type: string
                # sonarqube:
                #   description: SonarQube values
                #   type: object
                #   properties:
                #     token:
                #       description: SonarQube token
                #       type: string
                # grafana:
                #   description: Grafana values
                #   type: object
                #   properties:
                #     target:
                #       description: Grafana target url
                #       type: string
                #     token:
                #       description: Grafana token
                #       type: string
                # prometheus:
                #   description: Prometheus values
                #   type: object
                #   properties:
                #     target:
                #       description: Prometheus target
                #       type: string
                # providers:
                #   description: Krateo dashboard providers
                #   type: object
                #   properties:
                #     github:
                #       description: Krateo dashboard GitHub providers
                #       type: object
                #       properties:
                #         token:
                #           description: Krateo dashboard GitHub provider token
                #           type: string
                #         clientId:
                #           description: Krateo dashboard GitHub provider clientId
                #           type: string
                #         clientSecret:
                #           description: Krateo dashboard GitHub provider clientSecret
                #           type: string
                # kubernetes:
                #   description: Kubernetes values
                #   type: object
                #   properties:
                #     customResources:
                #       description: customResources defined for Kubernetes plugin
                #       type: array
                #       items:
                #         description: customResource for Kubernetes plugin
                #         type: object
                #         properties:
                #           group:
                #             description: customResource group
                #             type: string
                #           apiVersion:
                #             description: customResource apiVersion
                #             type: string
                #           plural:
                #             description: customResource plural
                #             type: string
                #     clusters:
                #       description: Kubernetes clusters visible from Krateo dashboard
                #       type: array
                #       items:
                #         description: Kubernetes cluster visible from Krateo dashboard
                #         type: object
                #         properties:
                #           url:
                #             description: Kubernetes cluster url
                #             type: string
                #           name:
                #             description: Kubernetes cluster name
                #             type: string
                #           authProvider:
                #             description: Kubernetes cluster authProvider
                #             type: string
                #           skipTLSVerify:
                #             description: Kubernetes cluster skipTLSVerify
                #             type: boolean
                # auth:
                #   description: Authentication methods
                #   type: object
                #   properties:
                #     github:
                #       description: Krateo dashboard GitHub providers
                #       type: object
                #       properties:
                #         token:
                #           description: Krateo dashboard GitHub provider token
                #           type: string
                #         clientId:
                #           description: Krateo dashboard GitHub provider clientId
                #           type: string
                #         clientSecret:
                #           description: Krateo dashboard GitHub provider clientSecret
                #           type: string
#              required:
#                - clusterVersion
