apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
#  name: demostacks.gcp-stack-template-plus.projectkerberus.io
  name: core.modules.krateoplatformops.io
spec:
  connectionSecretKeys:
    - kubeconfig
#  group: gcp-stack-template-plus.projectkerberus.io
  group: modules.krateoplatformops.io
  names:
#    kind: DemoStack
#    listKind: DemoStackList
#    plural: demostacks
#    singular: demostack
    kind: Core
    listKind: CoreList
    plural: core
    singular: core
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: Core module of Krateo PlatformOps
          type: object
#          properties:
#            spec:
#              type: object
#              properties:
#                argocdVersion:
#                  type: string
#                  description: ArgoCD version
#              required:
#                - clusterVersion
