apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: core.modules.krateoplatformops.io
spec:
  connectionSecretKeys:
    - kubeconfig
  group: modules.krateoplatformops.io
  names:
    kind: Core
    listKind: CoreList
    plural: core
    singular: core
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: Core module of Krateo PlatformOps
          type: object
          properties:
            spec:
              type: object
              properties:
                argocdVersion:
                  type: string
                  description: ArgoCD version
