---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: core.modules.krateo.io
spec:
  connectionSecretKeys:
    - kubeconfig
  group: modules.krateo.io
  names:
    kind: Core
    listKind: CoreList
    plural: core
    singular: core
  versions:
    - name: v1alpha1
      referenceable: true
      schema:
        openAPIV3Schema:
          description: Core module of Krateo PlatformOps
          properties:
            spec:
              properties:
                auth:
                  description: Authentication methods
                  type: object
                  properties:
                    github:
                      description: Krateo dashboard GitHub providers
                      type: object
                      properties:
                        clientId:
                          description: Krateo dashboard GitHub provider clientId
                          type: string
                        clientSecret:
                          description: Krateo dashboard GitHub provider clientSecret
                          type: string
                        token:
                          description: Krateo dashboard GitHub provider token
                          type: string
                ingress:
                  description: Ingress definition
                  type: object
                  properties:
                    enabled:
                      description: Ingress enabled
                      type: boolean
                      default: false
                    tls:
                      description: Ingress tls configuration
                      type: object
                      properties:
                        enabled:
                          description: Ingress tls enabled
                          type: boolean
                          default: false
                    annotations:
                      description: Ingress annotation
                      type: object
                      properties:
                        kubernetes.io/ingress.class:
                          description: Ingress class
                          type: string
                        kubernetes.io/tls-acme:
                          description: Ingress tls
                          type: string
                        ingress.kubernetes.io/force-ssl-redirect:
                          description: Ingress force-ssl-redirect
                          type: string
                lighthouse:
                  description: tool for improving the performance, quality, and correctness of your web apps
                  type: object
                  properties:
                    enabled:
                      description: lighthouse enabled boolean condition
                      type: boolean
                      default: false
                backendUrl:
                  description: Kerberus Dashboard backend url
                  type: string
                frontendUrl:
                  description: Kerberus Dashboard frontend url
                  type: string
                frontend:
                  description: Kerberus Dashboard frontend
                  type: object
                  properties:
                    service:
                      description: Kubernetes service for Kerberus Dashboard frontend
                      type: object
                      properties:
                        type:
                          description: Kubernetes service type for Kerberus Dashboard frontend
                          type: string
                          default: ClusterIP
                backend:
                  description: Kerberus Dashboard backend
                  type: object
                  properties:
                    service:
                      description: Kubernetes service for Kerberus Dashboard backend
                      type: object
                      properties:
                        type:
                          description: Kubernetes service type for Kerberus Dashboard backend
                          type: string
                          default: ClusterIP
                grafana:
                  description: Grafana values
                  type: object
                  properties:
                    target:
                      description: Grafana target url
                      type: string
                    token:
                      description: Grafana token
                      type: string
                kubernetes:
                  description: Kubernetes values
                  type: object
                  properties:
                    clusters:
                      description: Kubernetes clusters visible from Krateo dashboard
                      type: array
                      items:
                        description: Kubernetes cluster visible from Krateo dashboard
                        type: object
                        properties:
                          authProvider:
                            description: Kubernetes cluster authProvider
                            type: string
                          name:
                            description: Kubernetes cluster name
                            type: string
                          skipTLSVerify:
                            description: Kubernetes cluster skipTLSVerify
                            type: boolean
                          url:
                            description: Kubernetes cluster url
                            type: string
                    customResources:
                      description: customResources defined for Kubernetes plugin
                      type: array
                      items:
                        description: customResource for Kubernetes plugin
                        type: object
                        properties:
                          apiVersion:
                            description: customResource apiVersion
                            type: string
                          group:
                            description: customResource group
                            type: string
                          plural:
                            description: customResource plural
                            type: string
                organization:
                  description: Organization
                  type: string
                prometheus:
                  description: Prometheus values
                  type: object
                  properties:
                    target:
                      description: Prometheus target
                      type: string
                providers:
                  description: Krateo dashboard providers
                  type: object
                  properties:
                    github:
                      description: Krateo dashboard GitHub providers
                      type: object
                      properties:
                        clientId:
                          description: Krateo dashboard GitHub provider clientId
                          type: string
                        clientSecret:
                          description: Krateo dashboard GitHub provider clientSecret
                          type: string
                        token:
                          description: Krateo dashboard GitHub provider token
                          type: string
                sonarqube:
                  description: SonarQube values
                  type: object
                  properties:
                    token:
                      description: SonarQube token
                      type: string
                argo-cd:
                  description: Argo-cd helm chart values
                  type: object
                  properties:
                    version:
                      description: argo-cd helm chart version
                      type: string
                      default: 3.29.4
                    redis:
                      description: Argo-cd helm chart redis values
                      type: object
                      properties:
                        securityContext:
                          description: Argo-cd helm chart redis securityContext values
                          type: object
                          # properties:
                          #   runAsUser:
                          #     description: Argo-cd helm chart redis securityContext runAsUser value
                          #     type: integer
                krateo-dashboard:
                  description: krateo-dashboard helm chart values
                  type: object
                  properties:
                    version:
                      description: krateo-dashboard helm chart version
                      type: string
                      default: 0.3.131
                    keptn:
                      description: Keptn values
                      type: object
                      properties:
                        bridge:
                          description: Keptn bridge url
                          type: string
                        bridgeToken:
                          description: Keptn bridge token
                          type: string
                        api:
                          description: Keptn api url
                          type: string
                        apiToken:
                          description: Keptn api token
                          type: string
                    postgresql:
                      description: postgresql for krateo-dashboard-backend helm chart values
                      type: object
                      properties:
                        persistence:
                          description: persistent fields for PostgreSql
                          type: object
                          properties:
                            enabled:
                              description: Enable persistence using PVC
                              type: boolean
                            existingClaim:
                              description: Provide an existing `PersistentVolumeClaim`, the value is evaluated as a template. If defined, PVC must be created manually before volume will be bound. The value is evaluated as a template, so, for example, the name can depend on .Release or .Chart
                              type: string
                            mountPath:
                              description: The path the volume will be mounted at, useful when using different PostgreSQL images.
                              type: string
                            subPath:
                              description: The subdirectory of the volume to mount to. Useful in dev environments and one PV for multiple services.
                              type: string
                            storageClass:
                              description: PVC Storage Class for PostgreSQL volume.
                              type: string
                            accessModes:
                              description: PVC Access Mode for PostgreSQL volume
                              type: array
                            snapshotName:
                              description: Provide a VolumeSnapshot name which to create the PVC. The same snapshot will be used for the primary and any read replicas. ref: https://kubernetes.io/docs/concepts/storage/volume-snapshots/.
                              type: string
                            size:
                              description: PVC Storage Request for PostgreSQL volume
                              type: string
                            # annotations:
                            #   description: Annotations for the PVC
                            #   type: object
                            # selector:
                            #   description: Selector to match an existing Persistent Volume (this value is evaluated as a template).
                            #   type: object
                        volumePermissions:
                          description: Change the owner of the persist volume mountpoint to RunAsUser:fsGroup
                          type: object
                          properties:
                            enabled:
                              description: Enable init container that changes volume permissions in the data directory (for cases where the default k8s `runAsUser` and `fsUser` values do not work)
                              type: boolean
                            securityContext:
                              description: Init container Security Context
                              type: object
                              properties:
                                runAsUser:
                                  description: using `auto` is especially useful for OpenShift which has scc with dynamic userids (and 0 is not allowed).
                                  type: string
                        shmVolume:
                          description: shmVolume configuration
                          type: object
                          properties:
                            enabled:
                              description: Enable emptyDir volume for /dev/shm for primary and read replica(s) Pod(s). Set `shmVolume.enabled` to `true` to mount a new tmpfs volume to remove the above limitation.
                              type: boolean
                            chmod:
                              description: shmVolume.chmod configuration
                              type: object
                              properties:
                                enabled:
                                  description: Set to `true` to `chmod 777 /dev/shm` on a initContainer (ignored if `volumePermissions.enabled` is `false`)
                                  type: boolean
                        securityContext:
                          description: postgresql for krateo-dashboard-backend helm chart securityContext values
                          type: object
                          properties:
                            enabled:
                              description: postgresql for krateo-dashboard-backend helm chart securityContext enabled values
                              type: boolean
                        containerSecurityContext:
                          description: postgresql for krateo-dashboard-backend helm chart containerSecurityContext values
                          type: object
                          properties:
                            enabled:
                              description: postgresql for krateo-dashboard-backend helm chart containerSecurityContext enabled values
                              type: boolean
              type: object
          type: object
          required:
            - frontendUrl
            - backendUrl
      served: true
